### ISSUE TITLE
"Edit this Page" is missing.

### ISSUE THREAD

**Issue by eightysixed** [saschaleib/dokuwiki-template-ad-hominem#39] opened 2023-04-28 13:47 UTC
Uh-oh. We might have broke something after figuring out [this issue.](https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/37)

It appears that the `Edit this Page` link has disappeared since the last update. 

Screenshot below.
![E73B75A6-BB06-4AF5-9F2E-3A9C449320EC_4_5005_c](https://user-images.githubusercontent.com/1641513/235165041-d47bae5b-bee1-499a-8071-78a8e7a2c95b.jpeg)

**Comment by eightysixed** [comment] 2023-04-28 14:36
Oddly enough, `Create this Page` is also gone.

I'm logged in as an Admin user. What happened?

**Comment by eightysixed** [comment] 2023-04-28 15:09
> "Members of group admin currently have the following permissions in namespace *: Read, Edit, Create, Upload, Delete.
Note: The selected group or user has always full permissions because it is configured as superuser."

Something is funky.

**Comment by eightysixed** [comment] 2023-04-29 10:15
I figured it out.
How strange.
Cheers!
Closing.

**Comment by saschaleib** [comment] 2023-04-29 10:19
Hi and sorry for the late reply. I was already looking into this, and there seems to be an issue with the DokuWiki core - in fact the plugin just renders the items list from DokuWiki, doesn't do much on its own. I still want to keep this open, as I might find some time to trace this back to the core and maybe propose a fix to DokuWiki - but as this only seems to happen sometimes, this isn't really easy :-/

**Comment by eightysixed** [comment] 2023-04-29 14:52
Good morning!
Thank you for the reply.
Since you said you wanted to keep this open, I'll reopen the issue. If you find a permanent fix and pitch it to DokuWiki devs, make sure to also include that the included version of LESS should be updated as well, for the obvious reasons :)

**Comment by saschaleib** [comment] 2023-04-30 16:56
Thanks, but I mean the other issue – so I'll close this now as duplicate of #31.

**Closed** 2023-04-30 16:57 UTC
Labels: duplicate

**Comment by eightysixed** [comment] 2023-05-01 04:49
Oh dear, I didn't realize there was another issue about the same thing.

I'm not too up to speed on the German language.

But looking that over, side by side, he lost `Rename this Page` (which honestly I didn't think was possible via plug-in), but that's a different issue entirely.

So yeah, it's weird he lost that, and I lost my thing. 

I have it for now, but that's a weird coincidence.
